---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-new-capstone1
  labels:
    devops-new-capstone1: devops-new-capstone1
spec:
  replicas: 2
  selector:
    matchLabels:
     devops-new-capstone1: devops-new-capstone1
  template:
   metadata:
    labels:
     devops-new-capstone1: devops-new-capstone1
   spec:
    containers:
    - name: con2
      image: devrajdock/capsnewdevops:latest
      ports:
      - containerPort: 80
...
