---
apiVersion: v1
kind: Service
metadata:
  name: devops-capsnew1-svc
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31010
  selector:
    devops-new-capstone1: devops-new-capstone1
...
